export const PUBLISHATION_STATUSES = {
  PUBLISHED: "PUBLISHED",
  STORED_NOT_DISPATCHED: "STORED_NOT_DISPATCHED",
  FAILED_VALIDATION: "FAILED_VALIDATION",
  FAILED_STORE: "FAILED_STORE",
  FAILED_DISPATCH: "FAILED_DISPATCH",
};

export const PUBLISHATION_STATUS_LIST = Object.values(PUBLISHATION_STATUSES);

export const DEFAULT_PUBLISHER_VERSION = 1;

