export const ONBOARDING_EVENT_TYPES = {
  ONBOARDING_STARTED: "ONBOARDING_STARTED",
  ONBOARDING_STEP_COMPLETED: "ONBOARDING_STEP_COMPLETED",
  ONBOARDING_STEP_SKIPPED: "ONBOARDING_STEP_SKIPPED",
  ONBOARDING_COMPLETED: "ONBOARDING_COMPLETED",
};

export const SUPPORTED_ONBOARDING_EVENT_TYPES = Object.values(ONBOARDING_EVENT_TYPES);

