export const PREFERENCE_EVENT_TYPES = {
  PREFERENCE_RECORDED: "PREFERENCE_RECORDED",
  PREFERENCE_REVOKED: "PREFERENCE_REVOKED",
};

export const SUPPORTED_PREFERENCE_EVENT_TYPES = Object.values(PREFERENCE_EVENT_TYPES);
