export const INTERACTION_EVENT_TYPES = {
  INTERACTION_RECORDED: "INTERACTION_RECORDED",
  INTERACTION_NOTE_ADDED: "INTERACTION_NOTE_ADDED",
  INTERACTION_OUTCOME_RECORDED: "INTERACTION_OUTCOME_RECORDED",
  INTERACTION_FOLLOW_UP_SCHEDULED: "INTERACTION_FOLLOW_UP_SCHEDULED",
};

export const SUPPORTED_INTERACTION_EVENT_TYPES = Object.values(INTERACTION_EVENT_TYPES);
