import { buildOutcomeAutomationConfiguration } from "../../backend/core/industries/install/buildOutcomeAutomationConfiguration.js";
import { createIndustryPackage } from "../../backend/core/industries/IndustryPackage.js";
import { PROPERTY_MANAGEMENT_DASHBOARD_PRESENTATION } from "./presentation/PropertyManagementDashboardPresentation.js";
import {
  MCBRIDE_LIFECYCLE_TRANSITIONS,
  MCBRIDE_RELATIONSHIP_TYPES,
  terminologyByRelationshipFromRegistry,
} from "./config/mcbrideRelationshipRegistry.js";
import { MCBRIDE_QUALIFICATION_FIELD_SCHEMAS } from "./config/mcbrideQualificationSchema.js";
import { MCBRIDE_IMPORT_PROFILES } from "./config/mcbrideImportProfiles.js";

export const PM_AUTOMATION_CONFIGS = {
  prospectFollowUp: buildOutcomeAutomationConfiguration({
    outcomeValue: "follow_up_required",
    workType: "prospect_follow_up",
    title: "Prospect follow-up",
    description: "Follow up with prospect after interaction.",
    workItemIdPrefix: "work_pm_prospect_",
    actionId: "act_pm_prospect_follow_up",
    stageId: "stage_follow_up",
    queueId: "queue_follow_up",
    priority: "medium",
  }),
  showingCoordination: buildOutcomeAutomationConfiguration({
    outcomeValue: "showing_requested",
    workType: "showing_coordination",
    title: "Showing coordination",
    description: "Coordinate showing for interested party.",
    workItemIdPrefix: "work_pm_showing_",
    actionId: "act_pm_showing_coordination",
    stageId: "stage_execution",
    queueId: "queue_in_progress",
    priority: "high",
  }),
  maintenanceCoordination: buildOutcomeAutomationConfiguration({
    outcomeValue: "maintenance_coordination_required",
    workType: "maintenance_coordination",
    title: "Maintenance coordination",
    description: "Coordinate maintenance response for resident request.",
    workItemIdPrefix: "work_pm_maintenance_",
    actionId: "act_pm_maintenance_coordination",
    stageId: "stage_execution",
    queueId: "queue_in_progress",
    priority: "high",
  }),
  ownerApproval: buildOutcomeAutomationConfiguration({
    outcomeValue: "owner_approval_required",
    workType: "owner_response",
    title: "Owner approval response",
    description: "Prepare owner-facing response requiring authorization.",
    workItemIdPrefix: "work_pm_owner_",
    actionId: "act_pm_owner_approval",
    requiresApproval: true,
    stageId: "stage_approval",
    queueId: "queue_approvals",
    priority: "high",
  }),
  vendorAction: buildOutcomeAutomationConfiguration({
    outcomeValue: "vendor_action_required",
    workType: "vendor_follow_up",
    title: "Vendor follow-up",
    description: "Follow up with vendor on maintenance or service action.",
    workItemIdPrefix: "work_pm_vendor_",
    actionId: "act_pm_vendor_action",
    stageId: "stage_execution",
    queueId: "queue_in_progress",
    priority: "medium",
  }),
};

export const PM_RELATIONSHIP_FOLLOW_UP_RULES = [
  {
    id: "buyer_immediate_timeline_stale",
    relationshipTypes: ["BUYER"],
    priority: "high",
    reasonCode: "buyer_immediate_timeline_stale",
    reasonLabel: "Active Buyer — immediate timeline, no recent meaningful activity",
    staleAfterDays: 7,
    recurrenceDays: 7,
    conditions: {
      decisionTimeline: { equals: "immediate" },
    },
    targetWork: {
      workType: "prospect_follow_up",
      stageId: "stage_follow_up",
      queueId: "queue_follow_up",
      title: "Prospect follow-up",
      description: "Review relationship context and complete follow-up.",
    },
  },
  {
    id: "seller_prospect_near_term_stale",
    relationshipTypes: ["SELLER_PROSPECT"],
    priority: "high",
    reasonCode: "seller_prospect_near_term_stale",
    reasonLabel: "Seller Prospect — near-term timeline, follow-up needed",
    staleAfterDays: 14,
    recurrenceDays: 14,
    conditions: {
      decisionTimeline: { oneOf: ["immediate", "0_3_months"] },
    },
    targetWork: {
      workType: "prospect_follow_up",
      stageId: "stage_follow_up",
      queueId: "queue_follow_up",
      title: "Prospect follow-up",
      description: "Review seller prospect context and complete follow-up.",
    },
  },
  {
    id: "investor_property_interest_stale",
    relationshipTypes: ["INVESTOR"],
    priority: "medium",
    reasonCode: "investor_property_interest_stale",
    reasonLabel: "Investor — property interest recorded, no recent meaningful activity",
    staleAfterDays: 21,
    recurrenceDays: 21,
    conditions: {
      requiresPropertyInterest: true,
    },
    targetWork: {
      workType: "prospect_follow_up",
      stageId: "stage_follow_up",
      queueId: "queue_follow_up",
      title: "Prospect follow-up",
      description: "Review investor property interest and complete follow-up.",
    },
  },
  {
    id: "prospect_incomplete_qualification",
    relationshipTypes: ["PROSPECT"],
    priority: "medium",
    reasonCode: "prospect_incomplete_qualification",
    reasonLabel: "Prospect — qualification incomplete",
    staleAfterDays: 14,
    recurrenceDays: 14,
    conditions: {
      requiresIncompleteQualification: true,
    },
    targetWork: {
      workType: "prospect_follow_up",
      stageId: "stage_follow_up",
      queueId: "queue_follow_up",
      title: "Prospect follow-up",
      description: "Review prospect qualification gaps and complete follow-up.",
    },
  },
];

export const PROPERTY_MANAGEMENT_PACKAGE = createIndustryPackage({
  id: "pkg_property_management",
  name: "Property Management",
  displayName: "Property Management Operating System",
  description: "Complete property management business behavior through configuration and installation.",
  version: 1,
  terminology: {
    operatingSystemTitle: "Property Management Operating System",
    pages: {
      attentionTitle: "Needs decision",
      requestsTitle: "Opportunity & Service Requests",
      workTitle: "Work & Coordination",
      teamTitle: "Team & Digital Workforce",
      automationsTitle: "Automations",
      connectionsTitle: "Connections",
      setupTitle: "Workspace Setup",
      knowledgeTitle: "Knowledge",
    },
    party: {
      default: "Party",
      byRelationship: {
        ...terminologyByRelationshipFromRegistry(),
      },
    },
    request: {
      PROSPECT_INQUIRY: "Inquiry",
      MAINTENANCE_REQUEST: "Maintenance Request",
      OWNER_REQUEST: "Owner Request",
    },
    work: {
      prospect_follow_up: "Prospect Follow-Up",
      showing_coordination: "Showing Coordination",
      maintenance_coordination: "Maintenance Coordination",
      owner_response: "Owner Response",
      vendor_follow_up: "Vendor Follow-Up",
    },
    entityLabels: {
      property: "Property",
      unit: "Unit",
      lease: "Lease",
    },
  },
  capabilities: [
    { id: "lead_response", name: "Lead Response", description: "Respond to inbound prospect interest.", category: "customer_service" },
    { id: "showing_coordination", name: "Showing Coordination", description: "Schedule and coordinate property showings.", category: "scheduling" },
    { id: "application_follow_up", name: "Application Follow-Up", description: "Guide applicants through leasing process.", category: "operations" },
    { id: "resident_communication", name: "Resident Communication", description: "Communicate with residents on operational matters.", category: "communication" },
    { id: "owner_communication", name: "Owner Communication", description: "Prepare and coordinate owner communications.", category: "communication" },
    { id: "maintenance_coordination", name: "Maintenance Coordination", description: "Coordinate maintenance requests and vendors.", category: "operations" },
    { id: "vendor_coordination", name: "Vendor Coordination", description: "Coordinate vendor follow-up and service delivery.", category: "operations" },
    { id: "lease_administration", name: "Lease Administration", description: "Support lease lifecycle administration.", category: "compliance" },
    { id: "inspection_coordination", name: "Inspection Coordination", description: "Coordinate property inspections.", category: "operations" },
    { id: "delinquency_follow_up", name: "Delinquency Follow-Up", description: "Follow up on outstanding balances.", category: "finance" },
    { id: "renewal_coordination", name: "Renewal Coordination", description: "Coordinate lease renewals.", category: "operations" },
    { id: "document_review", name: "Document Review", description: "Review property management documents.", category: "review" },
  ],
  automationConfigurations: [
    { id: "pm_prospect_follow_up", configuration: PM_AUTOMATION_CONFIGS.prospectFollowUp },
    { id: "pm_showing_coordination", configuration: PM_AUTOMATION_CONFIGS.showingCoordination },
    { id: "pm_maintenance_coordination", configuration: PM_AUTOMATION_CONFIGS.maintenanceCoordination },
    { id: "pm_owner_approval", configuration: PM_AUTOMATION_CONFIGS.ownerApproval },
    { id: "pm_vendor_action", configuration: PM_AUTOMATION_CONFIGS.vendorAction },
  ],
  knowledgeCategories: [
    { id: "PM_COMPANY_POLICIES", name: "Company Policies", description: "Property management company policies.", sortOrder: 200, defaultTags: ["policies"] },
    { id: "PM_PROPERTIES_UNITS", name: "Properties and Units", description: "Property and unit reference information.", sortOrder: 210, defaultTags: ["properties"] },
    { id: "PM_LEASING", name: "Leasing", description: "Leasing procedures and criteria.", sortOrder: 220, defaultTags: ["leasing"] },
    { id: "PM_RESIDENT_COMMUNICATION", name: "Resident Communication", description: "Resident communication standards.", sortOrder: 230, defaultTags: ["resident"] },
    { id: "PM_OWNER_COMMUNICATION", name: "Owner Communication", description: "Owner communication standards.", sortOrder: 240, defaultTags: ["owner"] },
    { id: "PM_MAINTENANCE", name: "Maintenance", description: "Maintenance workflows and vendor standards.", sortOrder: 250, defaultTags: ["maintenance"] },
    { id: "PM_VENDORS", name: "Vendors", description: "Approved vendor information.", sortOrder: 260, defaultTags: ["vendors"] },
    { id: "PM_INSPECTIONS", name: "Inspections", description: "Inspection procedures.", sortOrder: 270, defaultTags: ["inspections"] },
    { id: "PM_APPLICATIONS", name: "Applications", description: "Rental application procedures.", sortOrder: 280, defaultTags: ["applications"] },
    { id: "PM_RENEWALS", name: "Renewals", description: "Lease renewal procedures.", sortOrder: 290, defaultTags: ["renewals"] },
    { id: "PM_COMPLIANCE", name: "Compliance", description: "Regulatory and compliance requirements.", sortOrder: 300, defaultTags: ["compliance"] },
    { id: "PM_EMERGENCY", name: "Emergency Procedures", description: "Emergency response procedures.", sortOrder: 310, defaultTags: ["emergency"] },
  ],
  knowledgeRequirements: [
    { id: "req_pm_leasing", categoryId: "PM_LEASING", description: "Leasing procedures must be configured before full readiness." },
    { id: "req_pm_maintenance", categoryId: "PM_MAINTENANCE", description: "Maintenance procedures required for operational readiness." },
    { id: "req_pm_owner_comm", categoryId: "PM_OWNER_COMMUNICATION", description: "Owner communication standards required." },
  ],
  employeeDefinitions: [
    {
      id: "pm_resident_prospect_coordinator",
      name: "Resident & Prospect Coordinator",
      role: "resident_prospect_coordination",
      capabilities: ["lead_response", "showing_coordination", "application_follow_up", "resident_communication"],
      knowledgeRequirements: ["PM_LEASING", "PM_RESIDENT_COMMUNICATION"],
      connectionDependencies: ["business_email"],
      integrationCapabilities: ["SEND_EMAIL"],
      requiresApproval: false,
    },
    {
      id: "pm_maintenance_coordinator",
      name: "Maintenance Coordinator",
      role: "maintenance_coordination",
      capabilities: ["maintenance_coordination", "vendor_coordination", "inspection_coordination"],
      knowledgeRequirements: ["PM_MAINTENANCE", "PM_VENDORS"],
      connectionDependencies: ["business_email", "sms_channel", "property_management_system"],
      integrationCapabilities: ["SEND_EMAIL", "SEND_SMS", "READ_EXTERNAL_RECORD"],
      requiresApproval: false,
    },
    {
      id: "pm_owner_success_coordinator",
      name: "Owner Success Coordinator",
      role: "owner_success",
      capabilities: ["owner_communication", "document_review", "renewal_coordination"],
      knowledgeRequirements: ["PM_OWNER_COMMUNICATION", "PM_RENEWALS"],
      connectionDependencies: ["business_email"],
      integrationCapabilities: ["SEND_EMAIL"],
      requiresApproval: true,
    },
  ],
  requestTypes: [
    { id: "PROSPECT_INQUIRY", displayName: "Prospect Inquiry", description: "Inbound interest from a prospective resident.", defaultPriority: "medium" },
    { id: "MAINTENANCE_REQUEST", displayName: "Maintenance Request", description: "Resident maintenance or repair request.", defaultPriority: "high" },
    { id: "OWNER_REQUEST", displayName: "Owner Request", description: "Request from property owner.", defaultPriority: "medium" },
  ],
  workTypes: [
    { id: "prospect_follow_up", displayName: "Prospect Follow-Up" },
    { id: "showing_coordination", displayName: "Showing Coordination" },
    { id: "application_follow_up", displayName: "Application Follow-Up" },
    { id: "maintenance_coordination", displayName: "Maintenance Coordination" },
    { id: "vendor_follow_up", displayName: "Vendor Follow-Up" },
    { id: "owner_response", displayName: "Owner Response" },
    { id: "inspection_coordination", displayName: "Inspection Coordination" },
    { id: "renewal_follow_up", displayName: "Renewal Follow-Up" },
  ],
  interactionOutcomes: [
    { id: "follow_up_required", displayName: "Follow-Up Required" },
    { id: "showing_requested", displayName: "Showing Requested" },
    { id: "application_started", displayName: "Application Started" },
    { id: "maintenance_coordination_required", displayName: "Maintenance Coordination Required" },
    { id: "vendor_action_required", displayName: "Vendor Action Required" },
    { id: "owner_approval_required", displayName: "Owner Approval Required" },
    { id: "resolved", displayName: "Resolved" },
    { id: "no_action_required", displayName: "No Action Required" },
  ],
  communicationIntents: [
    { id: "initial_prospect_response", displayName: "Initial Prospect Response", channel: "email" },
    { id: "showing_confirmation", displayName: "Showing Confirmation", channel: "email" },
    { id: "application_follow_up", displayName: "Application Follow-Up", channel: "email" },
    { id: "maintenance_acknowledgment", displayName: "Maintenance Acknowledgment", channel: "email" },
    { id: "maintenance_status_update", displayName: "Maintenance Status Update", channel: "email" },
    { id: "vendor_follow_up", displayName: "Vendor Follow-Up", channel: "email" },
    { id: "owner_approval_request", displayName: "Owner Approval Request", channel: "email" },
    { id: "inspection_reminder", displayName: "Inspection Reminder", channel: "email" },
    { id: "renewal_outreach", displayName: "Renewal Outreach", channel: "email" },
  ],
  onboardingSchema: {
    sections: [
      {
        id: "BUSINESS",
        title: "Business",
        fields: ["companyName", "portfolioType", "teamStructure", "operatingRegions", "businessHours"],
      },
      {
        id: "OPERATIONS",
        title: "Operations",
        fields: ["requestTypesHandled", "maintenanceWorkflow", "showingWorkflow", "applicationWorkflow", "ownerApprovalRules", "emergencyHandling"],
      },
      {
        id: "COMMUNICATIONS",
        title: "Communications",
        fields: ["businessEmailStatus", "smsStatus", "voiceStatus", "defaultSenderIdentities", "businessHoursBehavior"],
      },
      {
        id: "KNOWLEDGE",
        title: "Knowledge",
        fields: ["requiredKnowledgeCategories", "missingKnowledge", "documentsNeeded"],
      },
      {
        id: "TEAM",
        title: "Team",
        fields: ["humanMembers", "digitalEmployeesEnabled", "responsibilities", "approvalRoles"],
      },
      {
        id: "SYSTEMS",
        title: "Systems",
        fields: ["propertyManagementSystem", "calendar", "accounting", "documentStorage"],
      },
    ],
  },
  connectedSystemRequirements: [
    { id: "property_management_system", displayName: "Property Management System", requirementLevel: "recommended" },
    { id: "business_email", displayName: "Business Email", requirementLevel: "required" },
    { id: "sms_channel", displayName: "SMS Channel", requirementLevel: "optional" },
    { id: "voice_channel", displayName: "Voice Channel", requirementLevel: "optional" },
    { id: "calendar", displayName: "Calendar", requirementLevel: "recommended" },
    { id: "accounting", displayName: "Accounting", requirementLevel: "optional" },
    { id: "document_storage", displayName: "Document Storage", requirementLevel: "recommended" },
  ],
  connectionGuidance: [
    {
      id: "business_email",
      displayName: "Business Email",
      purpose: "Send and receive business communications.",
      requirementLevel: "required",
      connectionStatus: "not_connected",
      setupInstructions: "Connect your business email through the communications setup flow.",
      verificationInstructions: "Send a test message and confirm delivery in Communications OS.",
      troubleshootingGuidance: "Verify sender identity and domain authorization settings.",
      estimatedSetupComplexity: "low",
      requiredPermissions: ["send_email", "receive_email"],
    },
    {
      id: "property_management_system",
      displayName: "Property Management System",
      purpose: "Sync properties, units, leases, and resident data.",
      requirementLevel: "recommended",
      connectionStatus: "not_connected",
      setupInstructions: "Select your property management provider and complete OAuth or API key setup.",
      verificationInstructions: "Confirm property and unit records appear in workspace configuration.",
      troubleshootingGuidance: "Verify API credentials and required scopes with your provider.",
      estimatedSetupComplexity: "medium",
      requiredPermissions: ["read_properties", "read_residents"],
    },
  ],
  approvalPolicies: [
    { id: "owner_external_communication", description: "Owner-facing communications require authorized review.", configured: false },
    { id: "maintenance_vendor_dispatch", description: "Vendor dispatch above threshold requires approval.", configured: false },
  ],
  navigation: {
    modules: ["requests", "work", "team", "capabilities", "communications", "analytics", "knowledge", "engagement", "audiences"],
  },
  executiveExperience: {
    cockpitSignals: ["pending_approvals", "open_maintenance", "prospect_pipeline", "knowledge_gaps"],
    dashboardPresentation: PROPERTY_MANAGEMENT_DASHBOARD_PRESENTATION,
  },
  subjectTypes: [
    { id: "listing", displayName: "Listing", attributeSchema: { address: "string", price: "number", status: "string" } },
    { id: "property", displayName: "Property", attributeSchema: { address: "string", units: "number" } },
    { id: "unit", displayName: "Unit", attributeSchema: { unitNumber: "string", bedrooms: "number" } },
  ],
  qualificationFieldSchemas: MCBRIDE_QUALIFICATION_FIELD_SCHEMAS,
  relationshipTypes: MCBRIDE_RELATIONSHIP_TYPES,
  lifecycleTransitions: MCBRIDE_LIFECYCLE_TRANSITIONS,
  relationshipFollowUpRules: PM_RELATIONSHIP_FOLLOW_UP_RULES,
  inboundRouting: [
    { eventKind: "form_submission", requestType: "PROSPECT_INQUIRY", acknowledgmentIntentId: "initial_prospect_response" },
    { eventKind: "missed_call", requestType: "PROSPECT_INQUIRY", acknowledgmentIntentId: "initial_prospect_response" },
    {
      eventKind: "maintenance_form_submission",
      requestType: "MAINTENANCE_REQUEST",
      acknowledgmentIntentId: "maintenance_acknowledgment",
      partyRelationshipType: "RESIDENT",
      subjectRelationshipType: "RESIDENT_OF",
      defaultPriority: "high",
    },
  ],
  segmentTemplates: [
    {
      id: "interested_in_subject",
      name: "Interested in subject",
      targetEntityType: "Party",
      criteria: [{ fieldPath: "subjectCount", operator: "EXISTS" }],
    },
    {
      id: "interested_without_outcome",
      name: "Interested without completed outcome",
      targetEntityType: "Party",
      criteria: [
        { fieldPath: "subjectCount", operator: "EXISTS" },
        { fieldPath: "hasIncompleteOutcome", operator: "EQUALS", value: true },
      ],
    },
    {
      id: "matches_availability_preferences",
      name: "Matches availability preferences",
      targetEntityType: "Party",
      criteria: [
        { fieldPath: "requestCount", operator: "EXISTS" },
        { fieldPath: "interactionCount", operator: "EXISTS" },
      ],
    },
  ],
  importProfiles: MCBRIDE_IMPORT_PROFILES,
  metadata: { vertical: "property_management", universalMechanism: true },
});
