import { deepFreeze } from "../../../backend/core/workspace/_utils/deepFreeze.js";

export const PM_CAMPAIGN_TEMPLATES = deepFreeze([
  {
    id: "weekly_newsletter",
    name: "Weekly client newsletter",
    purpose: "Prepare a weekly relationship newsletter for eligible contacts.",
    channel: "email",
    audience: { type: "all_marketable_contacts" },
    approvalRequired: true,
    defaultSubject: "This week's real estate and property update",
    cta: "Reply if you want to talk through next steps with our team.",
    guardrails: [],
  },
  {
    id: "monthly_market_update",
    name: "Monthly market update",
    purpose: "Prepare a monthly informational update for marketable contacts.",
    channel: "email",
    audience: { type: "all_marketable_contacts" },
    approvalRequired: true,
    defaultSubject: "Monthly market update",
    cta: "Reply if you want a focused conversation about your plans.",
    guardrails: [],
  },
  {
    id: "property_announcement",
    name: "Property campaign",
    purpose: "Prepare property-linked outreach for people with canonical interest in a listing or property.",
    channel: "email",
    audience: { type: "subject_interest" },
    approvalRequired: true,
    defaultSubject: "A property update you may want to review",
    cta: "Reply if you would like details or a showing conversation.",
    guardrails: [],
  },
  {
    id: "cma_home_value",
    name: "CMA / home value outreach",
    purpose: "Prepare informational home-value outreach without implying a guaranteed appraisal.",
    channel: "email",
    audience: { type: "relationship_types", relationshipTypes: ["PAST_BUYER", "PAST_SELLER", "OWNER", "SELLER_PROSPECT"] },
    approvalRequired: true,
    defaultSubject: "Would a home value conversation be useful?",
    cta: "Reply if you would like to request a CMA or speak with the team.",
    guardrails: ["Informational only — not a formal appraisal."],
  },
  {
    id: "past_client_reactivation",
    name: "Past client reactivation",
    purpose: "Prepare outreach to past clients and inactive relationships with real relationship evidence.",
    channel: "email",
    audience: { type: "relationship_types", relationshipTypes: ["PAST_BUYER", "PAST_SELLER"] },
    approvalRequired: true,
    defaultSubject: "Checking in from our team",
    cta: "Reply if there is anything we can help with.",
    guardrails: [],
  },
  {
    id: "referral_outreach",
    name: "Referral outreach",
    purpose: "Prepare referral outreach only for contacts with actual qualifying relationship evidence.",
    channel: "email",
    audience: { type: "relationship_types", relationshipTypes: ["PAST_BUYER", "PAST_SELLER", "REFERRAL_SOURCE"] },
    approvalRequired: true,
    defaultSubject: "A quick referral question",
    cta: "Reply if someone you know could use a conversation with our team.",
    guardrails: [],
  },
]);

export const PM_RECURRING_OPERATION_DEFINITIONS = deepFreeze([
  {
    id: "weekly_client_newsletter",
    name: "Weekly Client Newsletter",
    cadence: { frequency: "weekly", interval: 1, dayOfWeek: 3 },
    enabled: true,
    produces: { kind: "campaign_preparation", campaignTemplateId: "weekly_newsletter" },
    description: "Prepare the weekly newsletter draft, audience, and review work.",
  },
  {
    id: "monthly_market_update",
    name: "Monthly Market Update",
    cadence: { frequency: "monthly", interval: 1, dayOfMonth: 1 },
    enabled: true,
    produces: { kind: "campaign_preparation", campaignTemplateId: "monthly_market_update" },
    description: "Prepare the monthly market update draft and audience review.",
  },
  {
    id: "past_client_reactivation_review",
    name: "Past Client Reactivation Review",
    cadence: { frequency: "monthly", interval: 1, dayOfMonth: 15 },
    enabled: true,
    produces: { kind: "campaign_preparation", campaignTemplateId: "past_client_reactivation" },
    description: "Review past-client and referral outreach opportunities.",
  },
]);
