import { deepFreeze } from "../../../backend/core/workspace/_utils/deepFreeze.js";
import { PROPERTY_MANAGEMENT_PACKAGE_MANIFEST } from "./propertyManagementPackageManifest.js";

export const MCBRIDE_MAGNA_MARE_CLIENT_TEMPLATE = deepFreeze({
  id: "client_template_mcbride_magna_mare",
  displayName: "McBride / Magna Mare Property Management Template",
  packageId: PROPERTY_MANAGEMENT_PACKAGE_MANIFEST.packageId,
  enabledCapabilities: [
    "crm_import_dry_run",
    "crm_import_commit",
    "relationship_classification",
    "property_listing_import",
    "person_property_linkage",
    "relationship_follow_up_queue",
    "relationship_follow_up_work_assignment",
    "relationship_follow_up_outcome_resolution",
    "knowledge_guided_draft_assistance",
    "relationship_operations_intelligence",
    "recurring_campaign_preparation",
    "campaign_audience_personalization",
    "campaign_approval_readiness",
  ],
  relationshipConfig: {
    relationshipTypes: ["PROSPECT", "BUYER", "SELLER_PROSPECT", "SELLER", "PAST_BUYER", "PAST_SELLER", "OWNER", "RESIDENT", "VENDOR", "REFERRAL_SOURCE", "INVESTOR"],
    additiveClassifications: true,
    explicitLifecycleTransitionsOnly: true,
  },
  qualificationQuestions: [
    "intent",
    "preferredLocation",
    "priceRange",
    "propertyType",
    "bedrooms",
    "bathrooms",
    "decisionTimeline",
    "financingStatus",
    "currentHomeOwnership",
    "needsToSellBeforeBuying",
    "bestTimeForFollowUp",
    "propertyOfInterest",
  ],
  importProfileRefs: {
    crm: ["generic_csv", "follow_up_boss_contacts", "appfolio_contacts_export"],
    subjects: ["mcbride_property_listing_csv", "magna_mare_property_listing_csv"],
  },
  followUpRuleSettings: {
    enabledRuleIds: ["buyer_immediate_timeline_stale", "seller_prospect_near_term_stale", "investor_property_interest_stale", "prospect_incomplete_qualification"],
    approvalRequiredBeforeWorkCreation: true,
    autoCreateFutureWork: false,
  },
  outcomeSettings: {
    enabledOutcomeIds: ["reached_still_interested", "no_response", "not_interested", "qualification_updated", "showing_requested", "follow_up_later"],
    completeWorkAfterOutcome: true,
    recordMemoryOnly: true,
  },
  draftWordingRules: {
    enabledTemplateIds: ["pm_buyer_follow_up_email", "pm_seller_prospect_follow_up_email", "pm_investor_follow_up_email", "pm_prospect_follow_up_email"],
    reviewOnly: true,
    sendAutomatically: false,
    guidance:
      "Use canonical relationship, qualification, consent, and linked-property context. Do not imply a specific property interest unless BusinessGraph linkage exists.",
  },
  knowledgeExpectations: {
    requiredCategoryIds: ["PM_LEASING", "PM_OWNER_COMMUNICATION", "PM_RESIDENT_COMMUNICATION"],
    recommendedCategoryIds: ["PM_PROPERTIES_UNITS", "PM_COMPANY_POLICIES", "PM_APPLICATIONS"],
  },
  intelligenceDashboardPriorities: [
    "follow_up_workload",
    "outcome_distribution",
    "property_demand",
    "future_follow_up_commitments",
    "draft_assistance_usage",
    "recurring_campaign_operations",
    "campaign_approval_readiness",
  ],
  recurringOperationRefs: ["weekly_client_newsletter", "monthly_market_update", "past_client_reactivation_review"],
  campaignTemplateRefs: ["weekly_newsletter", "monthly_market_update", "property_announcement", "cma_home_value", "past_client_reactivation", "referral_outreach"],
  onboardingChecklist: [
    "Upload CRM CSV and complete dry run review.",
    "Commit approved CRM import rows.",
    "Upload property/listing CSV and complete dry run review.",
    "Commit trusted property/listing rows and property-interest linkage.",
    "Review unresolved property interest rows.",
    "Configure team assignment ownership for follow-up work.",
    "Upload approved leasing and owner communication knowledge.",
    "Review imported consent state before any outreach.",
    "Complete a manual McBride walkthrough from People to Work to outcome to intelligence.",
    "Review recurring campaign preparation Work and queue a draft without provider sending.",
  ],
  dataRequirements: [
    { id: "crm_csv", label: "CRM export CSV", requiredForLaunch: true },
    { id: "property_listing_csv", label: "Property/listing CSV with trusted identity evidence", requiredForLaunch: true },
    { id: "approved_knowledge_docs", label: "Approved leasing and follow-up knowledge", requiredForLaunch: true },
    { id: "team_assignment_config", label: "Human team ownership and assignment config", requiredForLaunch: true },
    { id: "consent_review", label: "Consent and suppression review", requiredForLaunch: true },
    { id: "users_and_permissions", label: "Users with CRM/work permissions", requiredForLaunch: true },
  ],
  acceptanceFlow: [
    "CRM import creates classified people, qualification, consent, and notes.",
    "Property import creates canonical BusinessSubject records from trusted identity evidence only.",
    "Exact property interest matches create idempotent INTERESTED_IN graph linkage.",
    "People detail shows linked properties and Properties show interested people.",
    "A McBride user approves relationship follow-up work from candidate evidence.",
    "Assigned follow-up work is completed through an outcome and recorded as memory.",
    "Draft assistance prepares a reviewable message without sending.",
    "Relationship operations intelligence reflects workload, outcomes, and property demand.",
    "Recurring newsletter and campaign operations prepare evidence-backed audiences and draft communication for approval.",
    "Approved campaign communication is queued only; provider execution remains deferred.",
  ],
  deferredFutureCapabilities: [
    { id: "sms_inquiry_response", active: false },
    { id: "email_sending", active: false },
    { id: "appfolio_api_sync", active: false },
    { id: "website_form_automation", active: false },
    { id: "phone_and_missed_call_automation", active: false },
    { id: "provider_campaign_execution", active: false },
  ],
});
