import { deepFreeze } from "../../../backend/core/workspace/_utils/deepFreeze.js";

/**
 * Declarative qualification field contract for PROSPECT_INQUIRY (schema only — no validator).
 */
export const MCBRIDE_QUALIFICATION_FIELD_SCHEMA = deepFreeze({
  requestType: "PROSPECT_INQUIRY",
  fields: [
    {
      key: "intent",
      label: "Intent",
      valueType: "enum",
      allowedValues: ["buy", "sell", "rent", "invest", "unknown"],
      required: false,
      segmentable: true,
      sensitive: false,
    },
    {
      key: "preferredLocation",
      label: "Preferred location",
      valueType: "string",
      required: false,
      segmentable: true,
      sensitive: false,
    },
    {
      key: "priceRange",
      label: "Price range",
      valueType: "string",
      required: false,
      segmentable: true,
      sensitive: false,
    },
    {
      key: "propertyType",
      label: "Property type",
      valueType: "enum",
      allowedValues: ["single_family", "condo", "multi_family", "land", "commercial", "other"],
      required: false,
      segmentable: true,
      sensitive: false,
    },
    {
      key: "bedrooms",
      label: "Bedrooms",
      valueType: "number",
      required: false,
      segmentable: true,
      sensitive: false,
    },
    {
      key: "bathrooms",
      label: "Bathrooms",
      valueType: "number",
      required: false,
      segmentable: true,
      sensitive: false,
    },
    {
      key: "decisionTimeline",
      label: "Decision timeline",
      valueType: "enum",
      allowedValues: ["immediate", "0_3_months", "3_6_months", "6_12_months", "12_plus_months", "unknown"],
      required: false,
      segmentable: true,
      sensitive: false,
    },
    {
      key: "financingStatus",
      label: "Financing status",
      valueType: "enum",
      allowedValues: ["pre_approved", "needs_financing", "cash", "unknown"],
      required: false,
      segmentable: true,
      sensitive: false,
    },
    {
      key: "currentHomeOwnership",
      label: "Current home ownership",
      valueType: "enum",
      allowedValues: ["owns", "rents", "unknown"],
      required: false,
      segmentable: true,
      sensitive: false,
    },
    {
      key: "needsToSellBeforeBuying",
      label: "Needs to sell before buying",
      valueType: "boolean",
      required: false,
      segmentable: true,
      sensitive: false,
    },
    {
      key: "bestTimeForFollowUp",
      label: "Best time for follow-up",
      valueType: "string",
      required: false,
      segmentable: false,
      sensitive: false,
    },
    {
      key: "propertyOfInterest",
      label: "Property of interest",
      valueType: "subjectRef",
      required: false,
      segmentable: true,
      sensitive: false,
      canonicalSource: "request.subjectRefs[0]",
    },
    {
      key: "showingAvailability",
      label: "Showing availability",
      valueType: "string",
      required: false,
      segmentable: false,
      sensitive: false,
      canonicalSource: "interaction.outcome.showing_requested",
    },
    {
      key: "timeline",
      label: "Timeline",
      valueType: "string",
      required: false,
      segmentable: true,
      sensitive: false,
      deprecatedAliasFor: "decisionTimeline",
    },
  ],
});

export const MCBRIDE_QUALIFICATION_FIELD_SCHEMAS = deepFreeze([MCBRIDE_QUALIFICATION_FIELD_SCHEMA]);
