import { REQUEST_CHANNEL_TYPES } from "./RequestChannel.js";
import { REQUEST_STATUSES } from "./RequestStatus.js";

export const REQUEST_EVENT_TYPES = {
  REQUEST_RECEIVED: "REQUEST_RECEIVED",
  REQUEST_UPDATED: "REQUEST_UPDATED",
  REQUEST_QUALIFIED: "REQUEST_QUALIFIED",
  REQUEST_REJECTED: "REQUEST_REJECTED",
  REQUEST_CONVERTED: "REQUEST_CONVERTED",
  REQUEST_CLOSED: "REQUEST_CLOSED",
};

export const SUPPORTED_REQUEST_EVENT_TYPES = Object.values(REQUEST_EVENT_TYPES);

// Kept here for convenience + consistency with other runtimes.
export { REQUEST_STATUSES };
export { REQUEST_CHANNEL_TYPES };
