export const INTEGRATION_PLATFORM_EVENT_TYPES = {
  CONNECTION_CONNECTED: "CONNECTION_CONNECTED",
  CONNECTION_VERIFIED: "CONNECTION_VERIFIED",
  CONNECTION_FAILED: "CONNECTION_FAILED",
  EXTERNAL_ACTION_REQUESTED: "EXTERNAL_ACTION_REQUESTED",
  EXTERNAL_ACTION_COMPLETED: "EXTERNAL_ACTION_COMPLETED",
  EXTERNAL_ACTION_FAILED: "EXTERNAL_ACTION_FAILED",
  INBOUND_EVENT_RECEIVED: "INBOUND_EVENT_RECEIVED",
  INBOUND_EVENT_REJECTED: "INBOUND_EVENT_REJECTED",
};

export const SUPPORTED_INTEGRATION_PLATFORM_EVENT_TYPES = Object.values(INTEGRATION_PLATFORM_EVENT_TYPES);

export const INTEGRATION_OS_PUBLISHER_ID = "integration_os";
