export const ENGAGEMENT_VIEW_VERSION = 1;

export const TIMELINE_CATEGORIES = {
  PARTY: "party",
  RELATIONSHIP: "relationship",
  REQUEST: "request",
  WORK: "work",
  COMMUNICATION: "communication",
  INTERACTION: "interaction",
  AUTOMATION: "automation",
  APPROVAL: "approval",
};

export const TIMELINE_ITEM_TYPES = {
  PARTY_CREATED: "PARTY_CREATED",
  RELATIONSHIP_CREATED: "RELATIONSHIP_CREATED",
  REQUEST_CREATED: "REQUEST_CREATED",
  REQUEST_CONVERTED: "REQUEST_CONVERTED",
  WORK_CREATED: "WORK_CREATED",
  WORK_ASSIGNED: "WORK_ASSIGNED",
  COMMUNICATION_MESSAGE_DRAFTED: "COMMUNICATION_MESSAGE_DRAFTED",
  COMMUNICATION_MESSAGE_QUEUED: "COMMUNICATION_MESSAGE_QUEUED",
  COMMUNICATION_MESSAGE_SENT: "COMMUNICATION_MESSAGE_SENT",
  COMMUNICATION_MESSAGE_FAILED: "COMMUNICATION_MESSAGE_FAILED",
  COMMUNICATION_MESSAGE_RECEIVED: "COMMUNICATION_MESSAGE_RECEIVED",
  INTERACTION_RECORDED: "INTERACTION_RECORDED",
  INTERACTION_NOTE_ADDED: "INTERACTION_NOTE_ADDED",
  INTERACTION_OUTCOME_RECORDED: "INTERACTION_OUTCOME_RECORDED",
  FOLLOW_UP_SCHEDULED: "FOLLOW_UP_SCHEDULED",
  AUTOMATION_RUN_STARTED: "AUTOMATION_RUN_STARTED",
  AUTOMATION_RUN_COMPLETED: "AUTOMATION_RUN_COMPLETED",
  AUTOMATION_RUN_FAILED: "AUTOMATION_RUN_FAILED",
  APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
  APPROVAL_GRANTED: "APPROVAL_GRANTED",
  APPROVAL_REJECTED: "APPROVAL_REJECTED",
};

export const ATTENTION_CATEGORIES = {
  OVERDUE_FOLLOW_UP: "overdue_follow_up",
  FAILED_COMMUNICATION: "failed_communication",
  PENDING_APPROVAL: "pending_approval",
  HIGH_PRIORITY_WORK: "high_priority_work",
  UNANSWERED_INBOUND: "unanswered_inbound_communication",
  AUTOMATION_FAILURE: "automation_failure",
  OUTCOME_REQUIRES_ACTION: "outcome_requires_action",
};

export const NEXT_ACTION_TYPES = {
  COMPLETE_FOLLOW_UP: "complete_follow_up",
  REVIEW_WORK: "review_work",
  GRANT_APPROVAL: "grant_approval",
  RETRY_COMMUNICATION: "retry_communication",
  RESOLVE_AUTOMATION_FAILURE: "resolve_automation_failure",
  RESPOND_TO_INBOUND: "respond_to_inbound_communication",
};

export const FOLLOW_UP_STATUSES = {
  UPCOMING: "upcoming",
  OVERDUE: "overdue",
};
