export const COMMUNICATION_STATUSES = {
  DRAFT: "DRAFT",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  SENDING: "SENDING",
  SENT: "SENT",
  DELIVERED: "DELIVERED",
  OPENED: "OPENED",
  REPLIED: "REPLIED",
  FAILED: "FAILED",
};

export const COMMUNICATION_CHANNELS = {
  EMAIL: "email",
};

export const SUPPORTED_COMMUNICATION_STATUSES = Object.values(
  COMMUNICATION_STATUSES,
);

