export const APPROVAL_INTERNAL_EVENT_TYPES = {
  APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
  APPROVAL_GRANTED: "APPROVAL_GRANTED",
  APPROVAL_REJECTED: "APPROVAL_REJECTED",
  APPROVAL_CANCELLED: "APPROVAL_CANCELLED",
};

export const SUPPORTED_APPROVAL_INTERNAL_EVENT_TYPES = Object.values(APPROVAL_INTERNAL_EVENT_TYPES);

export const APPROVAL_REQUEST_STATUSES = {
  PENDING: "PENDING",
  GRANTED: "GRANTED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};
