export const RUNTIME_SNAPSHOT_KINDS = Object.freeze({
  CONNECTION: "connection",
  BUSINESS_GRAPH: "businessGraph",
  BUSINESS_SUBJECT: "businessSubject",
  REQUEST: "request",
  INTERACTION: "interaction",
  WORK: "work",
  COMMUNICATION: "communication",
  COMMUNICATION_PREFERENCE: "communicationPreference",
  ANALYTICS: "analytics",
  INTELLIGENCE_CANDIDATE: "intelligenceCandidate",
});

export const PROSPECT_LOOP_SNAPSHOT_KINDS = Object.freeze([
  RUNTIME_SNAPSHOT_KINDS.BUSINESS_GRAPH,
  RUNTIME_SNAPSHOT_KINDS.BUSINESS_SUBJECT,
  RUNTIME_SNAPSHOT_KINDS.REQUEST,
  RUNTIME_SNAPSHOT_KINDS.INTERACTION,
  RUNTIME_SNAPSHOT_KINDS.WORK,
  RUNTIME_SNAPSHOT_KINDS.COMMUNICATION,
  RUNTIME_SNAPSHOT_KINDS.COMMUNICATION_PREFERENCE,
  RUNTIME_SNAPSHOT_KINDS.ANALYTICS,
]);
