export default function Sidebar() {
  // Sprint 3: the application shell navigation is generated by the backend Workspace View Model.
  // `frontend/components/workspace/NavigationRenderer` owns the real sidebar.
  return null;
}

