export const COMPANY_EVENT_TYPES = {
  WEBSITE_INQUIRY_RECEIVED: "WEBSITE_INQUIRY_RECEIVED",

  BUYER_CREATED: "BUYER_CREATED",
  BUYER_UPDATED: "BUYER_UPDATED",

  WORK_CREATED: "WORK_CREATED",
  WORK_APPROVED: "WORK_APPROVED",
  WORK_REJECTED: "WORK_REJECTED",

  EMAIL_SENT: "EMAIL_SENT",

  KNOWLEDGE_CREATED: "KNOWLEDGE_CREATED",
  KNOWLEDGE_REVISION_CREATED: "KNOWLEDGE_REVISION_CREATED",
  KNOWLEDGE_ARCHIVED: "KNOWLEDGE_ARCHIVED",

  CATEGORY_CREATED: "CATEGORY_CREATED",
  CATEGORY_UPDATED: "CATEGORY_UPDATED",
  CATEGORY_ARCHIVED: "CATEGORY_ARCHIVED",
  CATEGORY_REORDERED: "CATEGORY_REORDERED",

  KNOWLEDGE_SOURCE_RECEIVED: "KNOWLEDGE_SOURCE_RECEIVED",
  KNOWLEDGE_INGESTION_STARTED: "KNOWLEDGE_INGESTION_STARTED",
  KNOWLEDGE_INGESTION_COMPLETED: "KNOWLEDGE_INGESTION_COMPLETED",
  KNOWLEDGE_INGESTION_FAILED: "KNOWLEDGE_INGESTION_FAILED",

  ACTIVITY_CREATED: "ACTIVITY_CREATED",
};

export const SUPPORTED_COMPANY_EVENT_TYPES = Object.values(COMPANY_EVENT_TYPES);

