export const COMPANY_EVENT_TYPES = {
  WEBSITE_INQUIRY_RECEIVED: "WEBSITE_INQUIRY_RECEIVED",

  BUYER_CREATED: "BUYER_CREATED",
  BUYER_UPDATED: "BUYER_UPDATED",

  WORK_CREATED: "WORK_CREATED",
  WORK_APPROVED: "WORK_APPROVED",
  WORK_REJECTED: "WORK_REJECTED",

  EMAIL_SENT: "EMAIL_SENT",

  ACTIVITY_CREATED: "ACTIVITY_CREATED",
};

export const SUPPORTED_COMPANY_EVENT_TYPES = Object.values(COMPANY_EVENT_TYPES);

