import { createIndustryTemplate } from "./IndustryTemplate.js";

const TEMPLATE_BY_ID = {
  RESIDENTIAL_PROPERTY: createIndustryTemplate({
    id: "RESIDENTIAL_PROPERTY",
    name: "Residential Property Management",
    description: "Neighborhood-centric residential property operations and walkthrough scheduling.",
    recommendedCapabilities: ["workspace", "digital_workforce", "communications", "knowledge"],
    recommendedDigitalEmployees: ["Property Interest Coordinator", "Leasing Assistant", "Marketing Coordinator"],
    recommendedKnowledgeCategories: ["FAQ", "SOP", "POLICIES", "PROPERTY_INFORMATION"],
    recommendedDashboardModules: ["pending_reviews", "completion_tracking"],
    recommendedKPIs: ["response_time", "walkthrough_success_rate"],
    recommendedIntegrations: ["website_intake", "email_provider"],
    futureOnboardingQuestions: ["Do you prioritize virtual or in-person walkthroughs?"],
    businessSegments: ["Buyer Services", "Owner Services"],
    servicesOffered: ["Walkthrough Scheduling", "Buyer Consultations", "Response Drafting"],
    customerTypes: ["Home Buyers", "Home Owners"],
    serviceAreas: ["Neighborhoods within your service radius"],
    operatingModel: "Guided, timeline-based workflow with deterministic drafts.",
    companySize: "Small to mid-market",
    languagesSupported: ["en"],
    emergencyServices: false,
    appointmentBased: true,
    remoteOrOnsite: "HYBRID",
    businessGoals: ["Increase walkthrough conversion rate", "Reduce response turnaround time"],
  }),
  COMMERCIAL_PROPERTY: createIndustryTemplate({
    id: "COMMERCIAL_PROPERTY",
    name: "Commercial Property Management",
    description: "B2B communications and leasing workflow optimization for commercial properties.",
    recommendedCapabilities: ["communications", "automation", "knowledge"],
    recommendedDigitalEmployees: ["Property Interest Coordinator", "Marketing Coordinator"],
    recommendedKnowledgeCategories: ["FAQ", "POLICIES", "PRICING", "PROPERTY_INFORMATION"],
    recommendedDashboardModules: ["pipeline_overview"],
    recommendedKPIs: ["lead_to_walkthrough_rate", "compliance_likelihood"],
    recommendedIntegrations: ["crm_next", "email_provider"],
    futureOnboardingQuestions: ["Do you require lease document generation?"],
    businessSegments: ["Lease Intake", "Lease Coordination"],
    servicesOffered: ["B2B Intake Triage", "Lease Follow-ups", "Document-ready drafting"],
    customerTypes: ["Commercial Tenants", "Business Leasing Teams"],
    serviceAreas: ["Citywide and nearby regions"],
    operatingModel: "Compliance-first triage with deterministic communication workflow.",
    companySize: "Mid-market",
    languagesSupported: ["en"],
    emergencyServices: false,
    appointmentBased: true,
    remoteOrOnsite: "REMOTE",
    businessGoals: ["Improve lead-to-walkthrough rate", "Maintain response compliance"],
  }),
  PERSONAL_INJURY_LAW: createIndustryTemplate({
    id: "PERSONAL_INJURY_LAW",
    name: "Personal Injury Law",
    description: "Case triage, compliance, and intake workflow recommendations for legal services.",
    recommendedCapabilities: ["workspace", "analytics", "knowledge"],
    recommendedDigitalEmployees: ["Intake Coordinator", "Legal Compliance Assistant"],
    recommendedKnowledgeCategories: ["COMPLIANCE", "FAQ", "SOP", "POLICIES"],
    recommendedDashboardModules: ["intake_health", "case_progress"],
    recommendedKPIs: ["intake_to_qualified_rate", "response_compliance_rate"],
    recommendedIntegrations: ["email_provider"],
    futureOnboardingQuestions: ["Do you have jurisdiction-specific intake forms?"],
    businessSegments: ["Intake", "Case Triage", "Compliance"],
    servicesOffered: ["Intake Intake Packet", "Case Progress Drafting", "Compliance guidance"],
    customerTypes: ["Injured Individuals", "Legal Teams"],
    serviceAreas: ["Jurisdiction coverage"],
    operatingModel: "Structured intake with deterministic case workflow.",
    companySize: "Small practice",
    languagesSupported: ["en"],
    emergencyServices: false,
    appointmentBased: true,
    remoteOrOnsite: "HYBRID",
    businessGoals: ["Increase intake to qualified rate", "Reduce response compliance gaps"],
  }),
  CORPORATE_LAW: createIndustryTemplate({
    id: "CORPORATE_LAW",
    name: "Corporate Law",
    description: "Transactional operations and document handling workflow for corporate matters.",
    recommendedCapabilities: ["workspace", "communications", "knowledge"],
    recommendedDigitalEmployees: ["Legal Operations Coordinator"],
    recommendedKnowledgeCategories: ["COMPLIANCE", "DOCUMENTS", "POLICIES", "FAQ"],
    recommendedDashboardModules: ["transaction_overview"],
    recommendedKPIs: ["approval_cycle_time", "document_completion_rate"],
    recommendedIntegrations: ["email_provider", "doc_storage"],
    futureOnboardingQuestions: ["Do you require NDA templates by industry?"],
    businessSegments: ["Client Intake", "Transactions", "Document Preparation"],
    servicesOffered: ["Transactional workflows", "Document-ready drafting", "Approval-ready outputs"],
    customerTypes: ["Corporate Clients", "In-house Counsel"],
    serviceAreas: ["Regional / national clients"],
    operatingModel: "Process-driven transaction workflow with deterministic communication.",
    companySize: "Mid to enterprise",
    languagesSupported: ["en"],
    emergencyServices: false,
    appointmentBased: false,
    remoteOrOnsite: "REMOTE",
    businessGoals: ["Improve approval cycle time", "Increase document completion rate"],
  }),
  GENERAL_DENTISTRY: createIndustryTemplate({
    id: "GENERAL_DENTISTRY",
    name: "General Dentistry",
    description: "Scheduling, patient communication, and appointment-based workflows.",
    recommendedCapabilities: ["workspace", "communications", "knowledge"],
    recommendedDigitalEmployees: ["Patient Intake Coordinator"],
    recommendedKnowledgeCategories: ["FAQ", "POLICIES", "MARKETING", "SOP"],
    recommendedDashboardModules: ["appointment_pipeline"],
    recommendedKPIs: ["show_rate", "reschedule_rate"],
    recommendedIntegrations: ["email_provider"],
    futureOnboardingQuestions: ["Do you offer emergency appointments?"],
    businessSegments: ["New Patient", "Scheduling", "Patient Communication"],
    servicesOffered: ["Appointment scheduling", "Patient messaging", "Visit readiness guidance"],
    customerTypes: ["Patients", "Caregivers"],
    serviceAreas: ["Local service area"],
    operatingModel: "Appointment-based scheduling with deterministic next-step communication.",
    companySize: "Small practice",
    languagesSupported: ["en"],
    emergencyServices: true,
    appointmentBased: true,
    remoteOrOnsite: "ON_SITE",
    businessGoals: ["Increase show rate", "Reduce reschedule rate"],
  }),
  ORTHODONTICS: createIndustryTemplate({
    id: "ORTHODONTICS",
    name: "Orthodontics",
    description: "Treatment stages guidance and marketing consistency for orthodontic practice.",
    recommendedCapabilities: ["communications", "knowledge", "analytics"],
    recommendedDigitalEmployees: ["Patient Intake Coordinator"],
    recommendedKnowledgeCategories: ["FAQ", "POLICIES", "MARKETING", "SOP"],
    recommendedDashboardModules: ["campaign_performance"],
    recommendedKPIs: ["consult_to_schedule_rate"],
    recommendedIntegrations: ["email_provider"],
    futureOnboardingQuestions: ["Do you have language-specific brochures?"],
    businessSegments: ["Consultation Pipeline", "Treatment Stages", "Marketing Consistency"],
    servicesOffered: ["Consult scheduling", "Treatment stage updates", "Marketing-ready responses"],
    customerTypes: ["Patients", "Referring clinics"],
    serviceAreas: ["Local / regional service area"],
    operatingModel: "Consult-to-schedule conversion focused workflow.",
    companySize: "Small to mid-market",
    languagesSupported: ["en"],
    emergencyServices: false,
    appointmentBased: true,
    remoteOrOnsite: "HYBRID",
    businessGoals: ["Increase consult_to_schedule rate"],
  }),
  MED_SPA: createIndustryTemplate({
    id: "MED_SPA",
    name: "Med Spa",
    description: "Service catalog, patient readiness, and appointment scheduling guidance.",
    recommendedCapabilities: ["communications", "knowledge", "workspace"],
    recommendedDigitalEmployees: ["Client Intake Coordinator", "Marketing Coordinator"],
    recommendedKnowledgeCategories: ["FAQ", "POLICIES", "MARKETING", "SOP", "PRICING"],
    recommendedDashboardModules: ["lead_pipeline"],
    recommendedKPIs: ["consult_to_appointment_rate"],
    recommendedIntegrations: ["email_provider"],
    futureOnboardingQuestions: ["Do you require pre-visit intake forms?"],
    businessSegments: ["Client Intake", "Treatment Booking", "Marketing Pipeline"],
    servicesOffered: ["Client readiness guidance", "Appointment scheduling", "Pre-visit follow-ups"],
    customerTypes: ["Clients", "Referral partners"],
    serviceAreas: ["Local service area"],
    operatingModel: "Client readiness plus deterministic timeline communication.",
    companySize: "Small to mid-market",
    languagesSupported: ["en"],
    emergencyServices: false,
    appointmentBased: true,
    remoteOrOnsite: "HYBRID",
    businessGoals: ["Increase consult_to_appointment rate"],
  }),
  MED_DEVICE_MANUFACTURING: createIndustryTemplate({
    id: "MED_DEVICE_MANUFACTURING",
    name: "Medical Device Manufacturing",
    description: "Compliance-focused responses and deterministic operations for manufacturing environments.",
    recommendedCapabilities: ["knowledge", "compliance", "analytics"],
    recommendedDigitalEmployees: ["Compliance Coordinator"],
    recommendedKnowledgeCategories: ["COMPLIANCE", "DOCUMENTS", "POLICIES", "FAQ"],
    recommendedDashboardModules: ["quality_ops_overview"],
    recommendedKPIs: ["audit_readiness_rate"],
    recommendedIntegrations: ["document_storage"],
    futureOnboardingQuestions: ["Do you require batch-specific compliance notes?"],
    businessSegments: ["Quality Operations", "Compliance", "Document Handling"],
    servicesOffered: ["Compliance guidance", "Quality workflow support", "Audit readiness drafting"],
    customerTypes: ["Internal Quality Teams", "Regulatory stakeholders"],
    serviceAreas: ["Manufacturing footprint"],
    operatingModel: "Compliance-first, deterministic drafting and documentation workflows.",
    companySize: "Enterprise",
    languagesSupported: ["en"],
    emergencyServices: false,
    appointmentBased: false,
    remoteOrOnsite: "REMOTE",
    businessGoals: ["Improve audit readiness rate"],
  }),
  CITY_GOVERNMENT: createIndustryTemplate({
    id: "CITY_GOVERNMENT",
    name: "City Government",
    description: "Public-facing guidance, service workflows, and operational rules for governmental services.",
    recommendedCapabilities: ["workspace", "knowledge", "communications"],
    recommendedDigitalEmployees: ["Public Affairs Coordinator"],
    recommendedKnowledgeCategories: ["FAQ", "POLICIES", "DOCUMENTS"],
    recommendedDashboardModules: ["service_requests_overview"],
    recommendedKPIs: ["response_time", "resolution_rate"],
    recommendedIntegrations: ["website_intake"],
    futureOnboardingQuestions: ["Do you require multilingual responses?"],
    businessSegments: ["Service Requests", "Public Communication"],
    servicesOffered: ["Deterministic service responses", "Public messaging support"],
    customerTypes: ["Residents", "Public stakeholders"],
    serviceAreas: ["City boundaries and services"],
    operatingModel: "Public-facing, compliance-aware service response workflow.",
    companySize: "Government org",
    languagesSupported: ["en"],
    emergencyServices: false,
    appointmentBased: false,
    remoteOrOnsite: "REMOTE",
    businessGoals: ["Improve response time", "Increase resolution rate"],
  }),
  DEFAULT: createIndustryTemplate({
    id: "DEFAULT",
    name: "General Industry Template",
    description: "Fallback operational recommendations for unknown industries.",
    recommendedCapabilities: ["workspace", "communications", "knowledge"],
    recommendedDigitalEmployees: ["General Coordinator"],
    recommendedKnowledgeCategories: ["FAQ", "POLICIES", "SOP"],
    recommendedDashboardModules: ["pipeline_overview"],
    recommendedKPIs: ["response_time"],
    recommendedIntegrations: ["email_provider"],
    futureOnboardingQuestions: ["Provide your industry-specific operating rules."],
    businessSegments: ["General Operations"],
    servicesOffered: ["General Support", "Scheduling", "Deterministic responses"],
    customerTypes: ["Customers"],
    serviceAreas: ["General service area"],
    operatingModel: "Deterministic workflow with guided next steps.",
    companySize: "General size",
    languagesSupported: ["en"],
    emergencyServices: false,
    appointmentBased: false,
    remoteOrOnsite: "HYBRID",
    businessGoals: ["Improve response quality and speed"],
  }),
};

export class IndustryTemplateRegistry {
  constructor() {
    this.byId = TEMPLATE_BY_ID;
  }

  getById(id) {
    return this.byId[String(id)] ?? this.byId.DEFAULT;
  }

  /**
   * Deterministically chooses a template based on primary industry string.
   * This is intentionally a simple keyword match for Sprint 4.
   */
  selectTemplateForIndustry(primaryIndustry) {
    const s = String(primaryIndustry ?? "").toLowerCase();
    if (!s) return this.byId.DEFAULT;
    if (s.includes("residential") || s.includes("property") || s.includes("management")) return this.byId.RESIDENTIAL_PROPERTY;
    if (s.includes("commercial")) return this.byId.COMMERCIAL_PROPERTY;
    if (s.includes("personal injury")) return this.byId.PERSONAL_INJURY_LAW;
    if (s.includes("corporate")) return this.byId.CORPORATE_LAW;
    if (s.includes("orthodont")) return this.byId.ORTHODONTICS;
    if (s.includes("med spa") || s.includes("med-spa") || s.includes("spa")) return this.byId.MED_SPA;
    if (s.includes("device") && s.includes("manufact")) return this.byId.MED_DEVICE_MANUFACTURING;
    if (s.includes("city") && s.includes("government")) return this.byId.CITY_GOVERNMENT;
    if (s.includes("dentistry") || s.includes("dental")) return this.byId.GENERAL_DENTISTRY;
    return this.byId.DEFAULT;
  }
}

