export const BUSINESS_SUBJECT_STATUSES = ["active", "inactive", "archived"];

export const BUSINESS_SUBJECT_EVENT_TYPES = {
  SUBJECT_CREATED: "SUBJECT_CREATED",
  SUBJECT_UPDATED: "SUBJECT_UPDATED",
  SUBJECT_ARCHIVED: "SUBJECT_ARCHIVED",
};

export const SUPPORTED_BUSINESS_SUBJECT_EVENT_TYPES = Object.values(BUSINESS_SUBJECT_EVENT_TYPES);
