export const WORKSPACE_DEFAULT_VERSION = "1";

// Built-in module registry (industry-agnostic).
// Industry templates recommend widgets/layouts later via ids (contract-only).
export const MODULE_REGISTRY = [
  {
    id: "mission_control",
    title: "Mission Control",
    description: "Executive command center for the owner.",
    navigation: { section: "Mission Control", item: "Mission Control" },
    supportedIndustries: ["any"],
    requiredCapabilities: [],
    requiredConnectedSystems: [],
    requiredKnowledge: [],
    requiredEmployees: [],
    defaultWidgets: [],
    defaultQueues: [],
    permissions: { read: ["manager"] },
    metadata: { kind: "mission_control" },
  },
  {
    id: "dashboard",
    title: "Dashboard",
    description: "High-level operational overview and priority signals.",
    navigation: { section: "Company", item: "Company" },
    supportedIndustries: ["any"],
    requiredCapabilities: [],
    requiredConnectedSystems: [],
    requiredKnowledge: [],
    requiredEmployees: [],
    defaultWidgets: ["summary_priority", "activity_timeline"],
    defaultQueues: [],
    permissions: { read: ["manager"] },
    metadata: { kind: "base" },
  },
  {
    id: "settings",
    title: "Settings",
    description: "Platform configuration and operational preferences.",
    navigation: { section: "Settings", item: "Settings" },
    supportedIndustries: ["any"],
    requiredCapabilities: [],
    requiredConnectedSystems: [],
    requiredKnowledge: [],
    requiredEmployees: [],
    defaultWidgets: [],
    defaultQueues: [],
    permissions: { read: ["manager"] },
    metadata: { kind: "settings" },
  },
  {
    id: "knowledge",
    title: "Knowledge",
    description: "Business knowledge categories and readiness visibility.",
    navigation: { section: "Knowledge", item: "Knowledge" },
    supportedIndustries: ["any"],
    requiredCapabilities: ["knowledge"],
    requiredConnectedSystems: ["Knowledge Repository"],
    requiredKnowledge: [],
    requiredEmployees: [],
    defaultWidgets: ["knowledge_overview"],
    defaultQueues: [],
    permissions: { read: ["manager", "employee"] },
    metadata: { kind: "knowledge" },
  },
  {
    id: "digital_workforce",
    title: "Digital Workforce",
    description: "Employee-ready operational layout for Digital Employees.",
    navigation: { section: "Team", item: "Team" },
    supportedIndustries: ["any"],
    requiredCapabilities: ["digital_workforce"],
    requiredConnectedSystems: [],
    requiredKnowledge: [],
    requiredEmployees: [],
    defaultWidgets: ["employee_status"],
    defaultQueues: [],
    permissions: { read: ["manager", "employee"] },
    metadata: { kind: "workforce" },
  },
  {
    id: "work_queue",
    title: "Work Queue",
    description: "Triage and progress view for inbound work items.",
    navigation: { section: "Work", item: "Work" },
    supportedIndustries: ["any"],
    requiredCapabilities: ["workspace"],
    requiredConnectedSystems: [],
    requiredKnowledge: [],
    requiredEmployees: [],
    defaultWidgets: ["queue_summary"],
    defaultQueues: ["work_queue"],
    permissions: { read: ["manager", "employee"] },
    metadata: { kind: "queue" },
  },
  {
    id: "communications",
    title: "Communications",
    description: "Branded communications readiness and future sending surfaces.",
    navigation: { section: "Work", item: "Work" },
    supportedIndustries: ["any"],
    requiredCapabilities: ["communications"],
    requiredConnectedSystems: [],
    requiredKnowledge: [],
    requiredEmployees: [],
    defaultWidgets: ["communication_status"],
    defaultQueues: [],
    permissions: { read: ["manager"] },
    metadata: { kind: "communications" },
  },
  {
    id: "connections",
    title: "Connections",
    description: "Connected systems availability and feature readiness.",
    navigation: { section: "Company", item: "Company" },
    supportedIndustries: ["any"],
    requiredCapabilities: ["integrations"],
    requiredConnectedSystems: ["Intake"],
    requiredKnowledge: [],
    requiredEmployees: [],
    defaultWidgets: ["connections_status"],
    defaultQueues: [],
    permissions: { read: ["manager"] },
    metadata: { kind: "connections" },
  },
  {
    id: "analytics",
    title: "Analytics",
    description: "Operational performance views and readiness insights.",
    navigation: { section: "Analytics", item: "Analytics" },
    supportedIndustries: ["any"],
    requiredCapabilities: ["analytics"],
    requiredConnectedSystems: [],
    requiredKnowledge: [],
    requiredEmployees: [],
    defaultWidgets: ["analytics_summary"],
    defaultQueues: [],
    permissions: { read: ["manager"] },
    metadata: { kind: "analytics" },
  },
  {
    id: "company_health",
    title: "Company Health",
    description: "Readiness and governance visibility across capabilities.",
    navigation: { section: "Company", item: "Company" },
    supportedIndustries: ["any"],
    requiredCapabilities: [],
    requiredConnectedSystems: [],
    requiredKnowledge: [],
    requiredEmployees: [],
    defaultWidgets: ["capability_health_overview"],
    defaultQueues: [],
    permissions: { read: ["manager"] },
    metadata: { kind: "health" },
  },
  {
    id: "recommendations",
    title: "Recommendations",
    description: "Deterministic next-step recommendations for the manager.",
    navigation: { section: "Work", item: "Work" },
    supportedIndustries: ["any"],
    requiredCapabilities: [],
    requiredConnectedSystems: [],
    requiredKnowledge: [],
    requiredEmployees: [],
    defaultWidgets: ["next_step_recommendations"],
    defaultQueues: [],
    permissions: { read: ["manager"] },
    metadata: { kind: "recommendations" },
  },
];

export const DEFAULT_WIDGET_TITLES = {
  summary_priority: { id: "summary_priority", title: "Priority Summary" },
  activity_timeline: { id: "activity_timeline", title: "Activity Timeline" },
  employee_status: { id: "employee_status", title: "Employee Progress" },
  queue_summary: { id: "queue_summary", title: "Queue Summary" },
  knowledge_overview: { id: "knowledge_overview", title: "Knowledge Overview" },
  communication_status: { id: "communication_status", title: "Communication Readiness" },
  connections_status: { id: "connections_status", title: "Connections Status" },
  analytics_summary: { id: "analytics_summary", title: "Analytics Summary" },
  capability_health_overview: { id: "capability_health_overview", title: "Capability Health" },
  next_step_recommendations: { id: "next_step_recommendations", title: "Next-Step Recommendations" },
};

