/**
 * Universal integration capabilities.
 * Core knows capabilities; providers know implementation.
 */
export const INTEGRATION_CAPABILITIES = {
  SEND_EMAIL: "SEND_EMAIL",
  SEND_SMS: "SEND_SMS",
  PLACE_VOICE_CALL: "PLACE_VOICE_CALL",
  RECEIVE_VOICE_CALL: "RECEIVE_VOICE_CALL",
  CREATE_CALENDAR_EVENT: "CREATE_CALENDAR_EVENT",
  UPDATE_CALENDAR_EVENT: "UPDATE_CALENDAR_EVENT",
  READ_CALENDAR_AVAILABILITY: "READ_CALENDAR_AVAILABILITY",
  CREATE_EXTERNAL_RECORD: "CREATE_EXTERNAL_RECORD",
  UPDATE_EXTERNAL_RECORD: "UPDATE_EXTERNAL_RECORD",
  READ_EXTERNAL_RECORD: "READ_EXTERNAL_RECORD",
  RECEIVE_WEBHOOK: "RECEIVE_WEBHOOK",
  INGEST_FORM_SUBMISSION: "INGEST_FORM_SUBMISSION",
  INGEST_DOCUMENT: "INGEST_DOCUMENT",
  SYNC_CONTACT: "SYNC_CONTACT",
  SYNC_WORK_ITEM: "SYNC_WORK_ITEM",
};

export const SUPPORTED_INTEGRATION_CAPABILITIES = Object.values(INTEGRATION_CAPABILITIES);
