export const COMMUNICATION_EVENT_TYPES = {
  COMMUNICATION_THREAD_CREATED: "COMMUNICATION_THREAD_CREATED",
  COMMUNICATION_MESSAGE_DRAFTED: "COMMUNICATION_MESSAGE_DRAFTED",
  COMMUNICATION_MESSAGE_QUEUED: "COMMUNICATION_MESSAGE_QUEUED",
  COMMUNICATION_MESSAGE_SENT: "COMMUNICATION_MESSAGE_SENT",
  COMMUNICATION_MESSAGE_DELIVERED: "COMMUNICATION_MESSAGE_DELIVERED",
  COMMUNICATION_MESSAGE_FAILED: "COMMUNICATION_MESSAGE_FAILED",
  COMMUNICATION_MESSAGE_RECEIVED: "COMMUNICATION_MESSAGE_RECEIVED",
  COMMUNICATION_THREAD_ARCHIVED: "COMMUNICATION_THREAD_ARCHIVED",
};

export const SUPPORTED_COMMUNICATION_EVENT_TYPES = Object.values(COMMUNICATION_EVENT_TYPES);

