export const SUBSCRIBER_RESULT_STATUSES = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
  DISABLED: "DISABLED",
};

export const SUBSCRIBER_RESULT_STATUS_LIST = Object.values(SUBSCRIBER_RESULT_STATUSES);

export const DEFAULT_SUBSCRIBER_PRIORITY = 0;
export const DEFAULT_SUBSCRIBER_ENABLED = true;

