export const CAPABILITY_EVENT_TYPES = {
  CAPABILITY_REGISTERED: "CAPABILITY_REGISTERED",
  CAPABILITY_UPDATED: "CAPABILITY_UPDATED",
  CAPABILITY_ARCHIVED: "CAPABILITY_ARCHIVED",
  CAPABILITY_PROVIDER_ADDED: "CAPABILITY_PROVIDER_ADDED",
  CAPABILITY_PROVIDER_REMOVED: "CAPABILITY_PROVIDER_REMOVED",
};

export const SUPPORTED_CAPABILITY_EVENT_TYPES = Object.values(CAPABILITY_EVENT_TYPES);

