export const AUTOMATION_DEFINITION_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED",
};

export const AUTOMATION_INTERNAL_EVENT_TYPES = {
  AUTOMATION_REGISTERED: "AUTOMATION_REGISTERED",
  AUTOMATION_UPDATED: "AUTOMATION_UPDATED",
  AUTOMATION_ACTIVATED: "AUTOMATION_ACTIVATED",
  AUTOMATION_DEACTIVATED: "AUTOMATION_DEACTIVATED",
  AUTOMATION_ARCHIVED: "AUTOMATION_ARCHIVED",
  AUTOMATION_RUN_STARTED: "AUTOMATION_RUN_STARTED",
  AUTOMATION_RUN_WAITING_FOR_APPROVAL: "AUTOMATION_RUN_WAITING_FOR_APPROVAL",
  AUTOMATION_RUN_COMPLETED: "AUTOMATION_RUN_COMPLETED",
  AUTOMATION_RUN_FAILED: "AUTOMATION_RUN_FAILED",
  AUTOMATION_RUN_CLOSED: "AUTOMATION_RUN_CLOSED",
};

export const SUPPORTED_AUTOMATION_INTERNAL_EVENT_TYPES = Object.values(AUTOMATION_INTERNAL_EVENT_TYPES);
