export const TEAM_EVENT_TYPES = {
  TEAM_MEMBER_CREATED: "TEAM_MEMBER_CREATED",
  TEAM_MEMBER_UPDATED: "TEAM_MEMBER_UPDATED",
  TEAM_MEMBER_ARCHIVED: "TEAM_MEMBER_ARCHIVED",

  TEAM_STATUS_CHANGED: "TEAM_STATUS_CHANGED",

  TEAM_WORK_ASSIGNED: "TEAM_WORK_ASSIGNED",
  TEAM_WORK_COMPLETED: "TEAM_WORK_COMPLETED",

  TEAM_DEPARTMENT_CREATED: "TEAM_DEPARTMENT_CREATED",
  TEAM_ROLE_CREATED: "TEAM_ROLE_CREATED",
};

export const SUPPORTED_TEAM_EVENT_TYPES = Object.values(TEAM_EVENT_TYPES);

