export const ANALYTICS_EVENT_TYPES = {
  ANALYTICS_METRIC_REGISTERED: "ANALYTICS_METRIC_REGISTERED",
  ANALYTICS_DATA_POINT_RECORDED: "ANALYTICS_DATA_POINT_RECORDED",
  ANALYTICS_DATA_POINT_CORRECTED: "ANALYTICS_DATA_POINT_CORRECTED",
  ANALYTICS_METRIC_ARCHIVED: "ANALYTICS_METRIC_ARCHIVED",
};

export const SUPPORTED_ANALYTICS_EVENT_TYPES = Object.values(ANALYTICS_EVENT_TYPES);

