export const BUSINESS_GRAPH_EVENT_TYPES = {
  PARTY_CREATED: "PARTY_CREATED",
  PARTY_UPDATED: "PARTY_UPDATED",
  PARTY_ARCHIVED: "PARTY_ARCHIVED",

  RELATIONSHIP_CREATED: "RELATIONSHIP_CREATED",
  RELATIONSHIP_UPDATED: "RELATIONSHIP_UPDATED",
  RELATIONSHIP_ENDED: "RELATIONSHIP_ENDED",
};

export const SUPPORTED_BUSINESS_GRAPH_EVENT_TYPES = Object.values(BUSINESS_GRAPH_EVENT_TYPES);
