import { INTEGRATION_CAPABILITIES } from "../capabilities/IntegrationCapability.js";
import { deepFreeze } from "../../workspace/_utils/deepFreeze.js";

/**
 * Universal mapping from industry connection type ids to enabled capabilities.
 * No industry-specific logic — connection types are package-declared identifiers.
 */
export const CONNECTION_TYPE_CAPABILITIES = deepFreeze({
  business_email: [INTEGRATION_CAPABILITIES.SEND_EMAIL],
  sms_channel: [INTEGRATION_CAPABILITIES.SEND_SMS],
  voice_channel: [INTEGRATION_CAPABILITIES.PLACE_VOICE_CALL, INTEGRATION_CAPABILITIES.RECEIVE_VOICE_CALL],
  calendar: [
    INTEGRATION_CAPABILITIES.CREATE_CALENDAR_EVENT,
    INTEGRATION_CAPABILITIES.UPDATE_CALENDAR_EVENT,
    INTEGRATION_CAPABILITIES.DELETE_CALENDAR_EVENT,
    INTEGRATION_CAPABILITIES.READ_CALENDAR_AVAILABILITY,
  ],
  meta_lead_ads: [
    INTEGRATION_CAPABILITIES.RECEIVE_WEBHOOK,
    INTEGRATION_CAPABILITIES.INGEST_FORM_SUBMISSION,
    INTEGRATION_CAPABILITIES.CREATE_EXTERNAL_RECORD,
  ],
  meta_ads: [
    INTEGRATION_CAPABILITIES.CREATE_AD_CAMPAIGN,
    INTEGRATION_CAPABILITIES.READ_AD_PERFORMANCE,
  ],
  google_ads: [
    INTEGRATION_CAPABILITIES.CREATE_AD_CAMPAIGN,
    INTEGRATION_CAPABILITIES.READ_AD_PERFORMANCE,
  ],
  google_search_console: [INTEGRATION_CAPABILITIES.READ_SEARCH_PERFORMANCE],
  social_screening: [INTEGRATION_CAPABILITIES.READ_EXTERNAL_RECORD],
  prospecting_enrichment: [INTEGRATION_CAPABILITIES.READ_EXTERNAL_RECORD],
  property_management_system: [
    INTEGRATION_CAPABILITIES.READ_EXTERNAL_RECORD,
    INTEGRATION_CAPABILITIES.UPDATE_EXTERNAL_RECORD,
    INTEGRATION_CAPABILITIES.CREATE_EXTERNAL_RECORD,
  ],
  accounting: [INTEGRATION_CAPABILITIES.READ_EXTERNAL_RECORD, INTEGRATION_CAPABILITIES.UPDATE_EXTERNAL_RECORD],
  document_storage: [INTEGRATION_CAPABILITIES.INGEST_DOCUMENT, INTEGRATION_CAPABILITIES.READ_EXTERNAL_RECORD],
});

export function getCapabilitiesForConnectionType(connectionType) {
  return CONNECTION_TYPE_CAPABILITIES[String(connectionType ?? "")] ?? [];
}
