export const CONNECTION_EVENT_TYPES = {
  CONNECTION_REGISTERED: "CONNECTION_REGISTERED",
  CONNECTION_CONFIGURATION_STARTED: "CONNECTION_CONFIGURATION_STARTED",
  CONNECTION_CONNECTED: "CONNECTION_CONNECTED",
  CONNECTION_VERIFIED: "CONNECTION_VERIFIED",
  CONNECTION_DEGRADED: "CONNECTION_DEGRADED",
  CONNECTION_FAILED: "CONNECTION_FAILED",
  CONNECTION_DISCONNECTED: "CONNECTION_DISCONNECTED",
  CONNECTION_ACTIVITY_RECORDED: "CONNECTION_ACTIVITY_RECORDED",
  CONNECTION_METADATA_UPDATED: "CONNECTION_METADATA_UPDATED",
};

export const SUPPORTED_CONNECTION_EVENT_TYPES = Object.values(CONNECTION_EVENT_TYPES);
