export const CONNECTION_STATUSES = {
  NOT_CONNECTED: "NOT_CONNECTED",
  CONFIGURING: "CONFIGURING",
  CONNECTED: "CONNECTED",
  DEGRADED: "DEGRADED",
  ERROR: "ERROR",
  DISCONNECTED: "DISCONNECTED",
};

export const SUPPORTED_CONNECTION_STATUSES = Object.values(CONNECTION_STATUSES);

export const CONNECTION_HEALTH_LEVELS = {
  HEALTHY: "HEALTHY",
  NEEDS_ATTENTION: "NEEDS_ATTENTION",
  DISCONNECTED: "DISCONNECTED",
  ERROR: "ERROR",
};

export function isValidConnectionStatus(status) {
  return SUPPORTED_CONNECTION_STATUSES.includes(String(status ?? ""));
}
