export const DISPATCH_RESULT_STATUSES = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
  DISABLED: "DISABLED",
};

export const DISPATCH_RESULT_STATUS_LIST = Object.values(DISPATCH_RESULT_STATUSES);

